# Generated by Django 5.0.6 on 2024-06-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_CategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_St', models.CharField(blank=True, max_length=100, null=True)),
                ('Sub_Category_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Sub_Category_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Sub_Category_Image', models.ImageField(blank=True, null=True, upload_to='Sub-Category Images')),
            ],
        ),
    ]
