# Generated by Django 5.0.6 on 2024-06-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_sub_categorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Select', models.CharField(blank=True, max_length=100, null=True)),
                ('Sub_Cat_Select', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_About', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Image', models.ImageField(blank=True, null=True, upload_to='Product Images')),
            ],
        ),
    ]
