# Generated by Django 5.0.6 on 2024-06-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Product_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
