# Generated by Django 5.0.6 on 2024-07-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_productdb_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Workout_Cat', models.CharField(blank=True, max_length=100, null=True)),
                ('Workout_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('Category_Image', models.ImageField(blank=True, null=True, upload_to='Workout_Category Images')),
            ],
        ),
    ]
