# Generated by Django 5.0.6 on 2024-07-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_workout_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout_Category',
            new_name='Workout_CategoryDB',
        ),
    ]
