# Generated by Django 5.0.6 on 2024-07-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_rename_workout_category_workout_categorydb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout_categorydb',
            old_name='Category_Image',
            new_name='Workout_Cat_Image',
        ),
    ]
