# Generated by Django 5.0.6 on 2024-07-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_rename_workout_categorydb_singwrk_cat_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Workout_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Sets', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Video', models.FileField(upload_to='Videos/')),
            ],
        ),
    ]
