# Generated by Django 5.0.6 on 2024-07-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_single_workouts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Single_Workouts',
            new_name='Single_WorkoutsDB',
        ),
    ]
