# Generated by Django 5.0.6 on 2024-07-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_rename_single_workouts_single_workoutsdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SingWrk_Cat_DB',
            new_name='Workout_Cat_DB',
        ),
    ]
