# Generated by Django 5.0.6 on 2024-07-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_rename_singwrk_cat_db_workout_cat_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_workoutsdb',
            name='Workout_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Workout Images'),
        ),
    ]
