# Generated by Django 5.0.6 on 2024-07-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_single_workoutsdb_workout_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Plan_Price', models.CharField(blank=True, max_length=100, null=True)),
                ('Plan_Description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
