# Generated by Django 5.0.6 on 2024-07-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_membership_plans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership_Plans',
            new_name='Membership_PlansDB',
        ),
    ]
