# Generated by Django 5.0.6 on 2024-07-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_alter_membership_plansdb_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership_plansdb',
            name='Plan_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
