# Generated by Django 5.0.6 on 2024-07-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_alter_membership_plansdb_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_workoutsdb',
            name='Workout_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Workout Images/'),
        ),
    ]
