# Generated by Django 5.0.6 on 2024-07-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_alter_single_workoutsdb_workout_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_Cat', models.CharField(blank=True, max_length=100, null=True)),
                ('Day', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
