# Generated by Django 5.0.6 on 2024-07-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0018_daydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Workout_Cat_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_Workout_Cat', models.CharField(blank=True, max_length=100, null=True)),
                ('Daily_Workout_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('Daily_Workout_Cat_Image', models.ImageField(blank=True, null=True, upload_to='Daily_Workout_Category Images')),
            ],
        ),
    ]
