# Generated by Django 5.0.6 on 2024-07-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0019_daily_workout_cat_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_WorkoutsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_Cat', models.CharField(blank=True, max_length=100, null=True)),
                ('Workout_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Sets', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Workout_Image', models.ImageField(blank=True, null=True, upload_to='Workout Images/')),
                ('Video', models.FileField(upload_to='Videos/')),
            ],
        ),
    ]
