# Generated by Django 5.0.6 on 2024-06-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fd_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('fd_Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('fd_Subject', models.CharField(blank=True, max_length=100, null=True)),
                ('fd_Message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
