# Generated by Django 5.0.6 on 2024-06-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_registerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tr_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Tr_Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Tr_Number', models.IntegerField(blank=True, null=True)),
                ('Tr_Course', models.CharField(blank=True, max_length=100, null=True)),
                ('Tr_Experience', models.CharField(blank=True, max_length=100, null=True)),
                ('Tr_Certification', models.CharField(blank=True, max_length=100, null=True)),
                ('Tr_Image', models.ImageField(blank=True, null=True, upload_to='Trainer Image')),
            ],
        ),
    ]
