# Generated by Django 5.0.6 on 2024-06-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0003_trainer_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainer_Register',
            new_name='Trainer_RegisterDB',
        ),
    ]
