# Generated by Django 5.0.6 on 2024-06-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_cartdb_ct_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Ct_Product_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
