# Generated by Django 5.0.6 on 2024-06-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0008_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_registerdb',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
