# Generated by Django 5.0.6 on 2024-07-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0010_trainerrequest_delete_trainer_registerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym_MemberDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Joining_Date', models.DateField(blank=True, max_length=100, null=True)),
                ('Select_Trainer', models.CharField(blank=True, max_length=100, null=True)),
                ('Select_Course', models.CharField(blank=True, max_length=100, null=True)),
                ('Select_Plan', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=100, null=True)),
                ('Height', models.CharField(blank=True, max_length=100, null=True)),
                ('Weight', models.CharField(blank=True, max_length=100, null=True)),
                ('Medical', models.CharField(blank=True, max_length=100, null=True)),
                ('Emergency_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Emergency_Phone', models.IntegerField(blank=True, null=True)),
                ('User_Session', models.CharField(blank=True, max_length=100, null=True)),
                ('Profile_Image', models.ImageField(blank=True, null=True, upload_to='Gym Members')),
                ('Payment_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
