# Generated by Django 5.0.6 on 2024-07-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0011_gym_memberdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Order_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
